GestorStock.WebApp/Controllers/AccesoController.cs
using Business;
using Entities;
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace GestorStock.WebApp.Controllers
{
    public class AccesoController : Controller
    {
        private readonly ILogger<AccesoController> _logger;

        private readonly UsuarioBusinnes _userBusinnes;

        public AccesoController(UsuarioBusinnes usuarioBusinnes, ILogger<AccesoController> logger)
        {
            _logger = logger;
            _userBusinnes = usuarioBusinnes;

        }
        public IActionResult Login()
        {
            if (User.Identity!.IsAuthenticated) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public IActionResult Login(string name, string password)
        {
            var user = new Usuario
            {
                Nombre = name

            };
            if (ModelState.IsValid)
            {

                var response = _userBusinnes.Login(name, password);
                if (response != null)
                {
                    List<Claim> claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, response.Nombre),
                        new Claim(ClaimTypes.NameIdentifier, response.UsuarioId.ToString())
                    };

                    ClaimsIdentity claimsIdentity= new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    AuthenticationProperties properties = new AuthenticationProperties()
                    {
                        AllowRefresh = true,
                    };

                    HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        properties
                        );

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewData["Mensaje"] = "Usuario o contraseña incorrecto/s";
                    return View();
                }

            }
            else
            {
                return View(user);
            }
        }

        public IActionResult Register() {
            if (User.Identity!.IsAuthenticated) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public IActionResult Register(string name, string password, string confirm)
        {
            
            if (password != confirm) {
                ViewData["Mensaje"] = "Las contraseñas no coinciden";
                var user = new Usuario
                {
                    Nombre = name
                };
                
                return View(user);
            }
            if (ModelState.IsValid)
            {
                var response = _userBusinnes.Register(name, password);
                if (response)
                {
                    
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewData["Mensaje"] = "No se pudo crear el usuario, error";
                    return View();
                }

            }
            else
            {
                return View();
            }
        }
    }
}

GestorStock.WebApp/Views/Acceso/Login.cshtml
@using Entities

@model Usuario

@{
    ViewData["Title"] = "Login";

    Layout = "~/Views/Shared/_LayoutLogin.cshtml"; ;
}


<div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Inicia Sesión</h3>
                    <p>Completa tus datos.</p>
                    <form class="requires-validation" novalidate asp-action="Login" asp-controller="Acceso" method="post">

                        <div class="col-md-12">
                            <input class="form-control" type="text" name="name" placeholder="Full Name" id="name" required asp-for="Nombre">
                            <div class="valid-feedback">Username field is valid!</div>
                            <div class="invalid-feedback">Username field cannot be blank!</div>
                        </div>


                        <div class="col-md-12">
                            <input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
                            <div class="valid-feedback">Password field is valid!</div>
                            <div class="invalid-feedback">Password field cannot be blank!</div>
                        </div>

                        

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">Acceder</button>
                        </div>

                        @if (ViewData["Mensaje"] != null)
                        {
                            <div class="alert alert-danger" role="alert">
                                @ViewData["Mensaje"]
                            </div>
                        }
                        <div class="mt-5" id="text">
                            ¿No tienes una cuenta?
                            <a asp-controller="Acceso" asp-action="Register">Registrate</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

GestorStock.WebApp/Views/Acceso/Register.cshtml
@using Entities

@model Usuario

@{
    ViewData["Title"] = "Register";

    Layout = "~/Views/Shared/_LayoutLogin.cshtml"; ;
}

   
<div class="form-body">
    <div class="row">
        <div class="form-holder">
            <div class="form-content">
                <div class="form-items">
                    <h3>Registrate</h3>
                    <p>Completa tus datos.</p>
                    <form class="requires-validation" novalidate asp-action="Register" asp-controller="Acceso" method="post">

                        <div class="col-md-12">
                            <input class="form-control" type="text" name="name" placeholder="Full Name" id="name" required asp-for="Nombre">
                            <div class="valid-feedback">Username field is valid!</div>
                            <div class="invalid-feedback">Username field cannot be blank!</div>
                        </div>


                        <div class="col-md-12">
                            <input class="form-control" type="password" name="password" id="password" placeholder="Password" required>
                            <div class="valid-feedback">Password field is valid!</div>
                            <div class="invalid-feedback">Password field cannot be blank!</div>
                        </div>

                        <div class="col-md-12">
                            <input class="form-control" type="password" name="confirm" id="confirm" placeholder="Confirm Password" required>
                            <div class="valid-feedback">Confirm password field is valid!</div>
                            <div class="invalid-feedback">Password field cannot be blank and must match password!</div>
                        </div>

                        <div class="form-button mt-3">
                            <button id="submit" type="submit" class="btn btn-primary">Registrarse</button>
                        </div>

                        @if (ViewData["Mensaje"] != null)
                        {
                            <div class="alert alert-danger" role="alert">
                                @ViewData["Mensaje"]
                            </div>
                        }
                        <div class="mt-5" id="text">
                            ¿Ya tienes una cuenta?
                            <a asp-controller="Acceso" asp-action="Login">Iniciar Sesión</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>