GestorStock.WebApp/Controllers/CompraController.cs
using Business;
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Globalization;
using X.PagedList;

namespace GestorStock.WebApp.Controllers
{
    public class CompraController : Controller
    {
        private readonly ILogger<CompraController> _logger;

        private readonly CompraBusinnes _compraBusinnes;

        private readonly ProductoBusinnes _productoBusinnes;


        public CompraController(CompraBusinnes compraBusinnes, ProductoBusinnes productoBusinnes,
            ILogger<CompraController> logger)
        {
            _logger = logger;

            //Para hacer Inyección de dependencias

            _compraBusinnes = compraBusinnes;

            _productoBusinnes = productoBusinnes;
        }
        public IActionResult Index(string sortOrder, string currentFilter, string buscar, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "name_desc";
            ViewBag.DateSortParm = sortOrder == "Date" ? "" : "Date";

            if (buscar != null)
            {
                page = 1;
            }
            else
            {
                buscar = currentFilter;
            }

            ViewBag.CurrentFilter = buscar;

            var compras = _compraBusinnes.GetAll(sortOrder, buscar);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(compras.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Cargar(int categoryId)
        {
            //EESTE METODO SOLO DEVUELVE LA VISTA
            var categorias = _compraBusinnes.GetCategories();
            var lst = (from c in categorias
                      select new SelectListItem
                      {
                          Value = c.CategoriaId.ToString(),
                          Text = c.Nombre
                      }).ToList();
            ViewBag.Categorias = lst;

            var productos = _compraBusinnes.GetProductsByCategoryId(categoryId);
            //ViewBag.Productos
            return View();
        }

        [HttpPost]
        public IActionResult Cargar(Compra compra, string producto)
        {
            //ESTE METODO RECIBE EL OBJETO PARA GUARDARLO EN LA DB
            ModelState.Remove("CompraId");
            ModelState.Remove("ProductoId");
            compra.ProductoId = Int32.Parse(producto);

            var categorias = _compraBusinnes.GetCategories();
            var lst = (from c in categorias
                       select new SelectListItem
                       {
                           Value = c.CategoriaId.ToString(),
                           Text = c.Nombre
                       }).ToList();
            ViewBag.Categorias = lst;



            if (ModelState.IsValid)
            {
                var response = _compraBusinnes.Create(compra);
                var respHabilitado = _productoBusinnes.SetHabilitado(compra.ProductoId);
                if (response && respHabilitado)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }

            }

            else
            {
                return View(compra);
            }
        }

        [HttpGet]
        public JsonResult Producto(int categoriaId)
        {
            List<ElementJsonIntKey> lista = new List<ElementJsonIntKey>();

            var lst = _compraBusinnes.GetProductsByCategoryId(categoriaId);

            lista = (from p in lst
                             select new ElementJsonIntKey
                             {
                                 Value= p.ProductoId,
                                 Text = p.Nombre
                             }).ToList();

            return Json(lista);
        }

        public class ElementJsonIntKey
        {
            public int Value { get; set; }
            public string Text { get; set;}
        }


    }
}

GestorStock.WebApp/Controllers/VentaController.cs
using Business;
using Entities;
using Entities.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using X.PagedList;


namespace GestorStock.WebApp.Controllers
{
    public class VentaController : Controller
    {

        private readonly ILogger<VentaController> _logger;

        private readonly VentaBusinnes _ventaBusinnes;

        private readonly ProductoBusinnes _productoBusinnes;

        public VentaController(VentaBusinnes ventaBusinnes, ProductoBusinnes productoBusinnes,
            ILogger<VentaController> logger)
        {
            _logger = logger;

            //Para hacer Inyección de dependencias

            _ventaBusinnes = ventaBusinnes;

            _productoBusinnes = productoBusinnes;
        }
        public IActionResult Index(string sortOrder, string buscar, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "name_desc";
            ViewBag.DateSortParm = sortOrder == "Date" ? "" : "Date";

            if (buscar != null)
            {
                page = 1;
            }
            else
            {
                buscar = currentFilter;
            }

            ViewBag.CurrentFilter = buscar;
            
            var ventas = _ventaBusinnes.GetAll(sortOrder, buscar);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(ventas.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Cargar()
        {
            var categorias = _ventaBusinnes.GetCategories();
            var lst = (from c in categorias
                       select new SelectListItem
                       {
                           Value = c.CategoriaId.ToString(),
                           Text = c.Nombre
                       }).ToList();
            ViewBag.Categorias = lst;
            ViewBag.StockOk = "display:none";
            //ESTE METODO SOLO DEVUELVE LA VISTA
            return View();
        }

        [HttpPost]
        public IActionResult Cargar(Venta venta, string producto)
        {
            venta.ProductoId = Int32.Parse(producto);
            var categorias = _productoBusinnes.GetCategoriesByProdId(venta.ProductoId);
            var lst = (from c in categorias
                       select new SelectListItem
                       {
                           Value = c.CategoriaId.ToString(),
                           Text = c.Nombre
                       }).ToList();

            ViewBag.Categorias = lst;

            var result = _productoBusinnes.GetStock(venta.ProductoId);

            ViewBag.StockOk = "display:none";


            if (result>=venta.Cantidad && result>0)
            
            {
                var response = _ventaBusinnes.Create(venta);//ESTE METODO RECIBE EL OBJETO PARA GUARDARLO EN LA DB
                
                if (response)
                {   
                    if(result==venta.Cantidad)
                    {
                        _productoBusinnes.SetHabilitado(venta.ProductoId);
                    }
                    
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {   
                ViewBag.StockOk= "display:block;color:red";
                ViewData["Mensaje"] = "Error de stock";
                ViewBag.Alert = "Lo sentimos, no hay Stock. VUELVE A SELECCIONAR EL PRODUCTO";
                return View(venta);
            }
            
            
            
        }

        [HttpGet]
        public JsonResult Producto(int categoriaId)
        {
            List<ElementJsonIntKey> lista = new List<ElementJsonIntKey>();

            var lst = _ventaBusinnes.GetProductsByCategoryId(categoriaId);

            lista = (from p in lst
                     select new ElementJsonIntKey
                     {
                         Value = p.ProductoId,
                         Text = p.Nombre
                     }).ToList();

            return Json(lista);
        }

        public class ElementJsonIntKey
        {
            public int Value { get; set; }
            public string Text { get; set; }
        }

    }
}

GestorStock.WebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestorStock.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorStock.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestorStock.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="Index">Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Index">Ventas</a>
                        </li>                        
                    </ul>
                    <ul class="navbar-nav flex-grow-1 d-sm-inline-flex justify-content-end" id="logout">
                        <li class="nav-item ps-sm-2 pe-2 pt-2 pb-2">
                            @if (User.Identity!.IsAuthenticated)
                            {
                                @User.Claims.Where(c => c.Type == ClaimTypes.Name).Select(c => c.Value).SingleOrDefault()
                            }
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Cerrar Sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorStock.WebApp - Rebeca Ozuna
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestorStock.WebApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - GestorStock.WebApp</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/Register.css">
        <link rel="stylesheet" href="~/GestorStock.WebApp.styles.css" asp-append-version="true" />
    </head>
    <body>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/register.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
    
</html>